/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

wyjscie *
convert_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;

	/*
	 * insert server code here
	 */

	for (int i=0, j =0; i < strlen(argp->buffer); ++i, j+=2)
	{
		sprintf(result.buffer + j, "%02x", argp->buffer[i] & 0xff);
	}

	return &result;
}
